runtime: python37
service: ncei-wind
env_variables:
    URL: https://www.ncei.noaa.gov/access/services/data/v1?dataset=global-marine&dataTypes=WIND_DIR,WIND_SPEED&stations=AUCE&startDate=2016-01-01&endDate=2016-01-02&boundingBox=90,-180,-90,180
    PROJECT: $PROJECT
    TOPIC: ncei-wind
    SUBSCRIPTION: ncei-wind
    DATASET: ncei
    TABLE: wind
