steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'eu.gcr.io/${PROJECT_ID}/${_IMAGE_NAME}', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/${PROJECT_ID}/${_IMAGE_NAME}']
- name: 'eu.gcr.io/${PROJECT_ID}/${_IMAGE_NAME}'
  entrypoint: sh
  args: ['-c', 'python3 generate.py']
substitutions:
  _IMAGE_NAME: ml-generate-climate-news
