apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: iris-
spec:
  entrypoint: iris
  templates:
  - name: iris
    container:
      image: eu.gcr.io/climate-poc-01/ml-iris:latest
      command: [python]
      args: ["iris.py"]
